### ISSUE TITLE
Kubernetes cronjob email alerts setup

### ISSUE THREAD

**Issue by arthuersundar** [tdickman/kubernetes-cron#9]
I have few cronjobs configured and running in kubernetes. How to setup up cronjob email alerts for success or failure in kubernetes.

**Comment by arthuersundar** [comment]
I would like to know how to genereate emails alerts for cronjobs configured in kubernetes

**Comment by tdickman** [comment]
Sorry, that is not something this was built to support. You would need to setup something to run in your cluster and send alerts when jobs fail. Something like [searchlight](https://github.com/appscode/searchlight) looks interesting, but not sure if it supports jobs / cronjobs.
